name: Create Release PR

on:
  pull_request:
    types:
      - closed

jobs:
  create_prerelease:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'prerelease')) }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Install Ruby 3.3
      uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # tag v1.190.0
      with:
        ruby-version: 3.3

    - name: Checkout code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2

    - run: bundle

    - name: Set agent version
      run: echo "agent_version=$(bundle exec rake newrelic:version:current)" >> $GITHUB_ENV

    - name: Create pull request
      run: gh pr create --draft --base "main" --title "$TITLE" --body "$BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TITLE: "Release ${{ env.agent_version }}"
        BODY: "Automated PR for ${{ env.agent_version}} release"
