name: Slack Notifications

on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  gem_notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2 # tag v1.149.0
        with:
          ruby-version: 3.2
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0
      - run: gem install httparty
      - name: Check for outdated gems 
        run: ruby .github/workflows/scripts/slack_notifications/gem_notifier.rb ${{ env.gems }}
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
          gems:
            "activerecord 
            bunny
            dalli
            delayed_job
            excon
            http
            httpclient
            mongo
            puma
            sidekiq
            sinatra
            tilt
            rack
            rails
            rake 
            redis
            resque
            unicorn"

  cve_notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2 # tag v1.149.0
        with:
          ruby-version: 3.2
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0
      - run: gem install httparty
      - run: gem install feedjira
      - name: Check for CVEs
        run: ruby .github/workflows/scripts/slack_notifications/cve_notifier.rb
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
