name: Slack Notifications

on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  gem_notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # tag v1.190.0
        with:
          ruby-version: 3.3
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2
      - run: gem install httparty
      - name: Check for outdated gems
        run: ruby .github/workflows/scripts/slack_notifications/gem_notifier.rb ${{ env.gems }}
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
          gems:
            "activerecord
            bunny
            dalli
            delayed_job
            elasticsearch
            excon
            grape
            http
            httpclient
            mongo
            puma
            rack
            rails
            rake
            redis
            resque
            roda
            ruby-openai
            sidekiq
            sinatra
            stripe
            tilt
            unicorn
            view_component"

  cve_notifications:
    runs-on: ubuntu-22.04
    steps:
      - uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # tag v1.190.0
        with:
          ruby-version: 3.3
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2
      - run: gem install httparty
      - run: gem install feedjira
      - name: Check for CVEs
        run: ruby .github/workflows/scripts/slack_notifications/cve_notifier.rb
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
