name: Snyk Check

on:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2 # tag v1.149.0
        with:
          ruby-version: 3.2
      - name: Bundle
        run: bundle install
      - name: Run Snyk
        uses: snyk/actions/ruby@7fad562681122205233d1242c3bb39598c5393da # tag v.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
