name: zzztesting
on:
  pull_request:
  push:
    branches:
      - zzztesting
  workflow_dispatch:

jobs:
  shared_values:
    runs-on: ubuntu-22.04
    steps:
      - id: step1
        run: echo "THEKEY=theval" >> $GITHUB_OUTPUT
    outputs:
      thekey: ${{ steps.step1.outputs.THEKEY }}

  demo:
    runs-on: ubuntu-22.04
    needs: [shared_values]
    steps:
      - run: echo "THEKEY's value is ${{ needs.shared_values.outputs.thekey }}"
