name: zzztesting
on:
  pull_request:
  push:
    branches:
      - zzztesting
  workflow_dispatch:

jobs:
  set_vars:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "THEKEY=theval" >> $GITHUB_ENV

  use_vars:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "THEKEY's value is $THEKEY"
