name: zzztesting
on:
  pull_request:
  push:
    branches:
      - zzztesting
  workflow_dispatch:

jobs:
  # shared_values:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - id: step1
  #       run: echo "THEKEY=theval" >> $GITHUB_OUTPUT
  #   outputs:
  #     thekey: ${{ steps.step1.outputs.THEKEY }}

  shared_values:
    runs-on: ubuntu-latest
    steps:
      - id: gather
        run: |
          curl -O https://raw.githubusercontent.com/newrelic/newrelic-ruby-agent/dev/.github/workflows/scripts/gather_action_versions.sh
          ./gather_action_versions.sh
    outputs:
      setup_ruby_sha: ${{ steps.gather.outputs.SETUP_RUBY_SHA }}
      checkout_sha: ${{ steps.gather.outputs.CHECKOUT_SHA }}

  demo:
    runs-on: ubuntu-22.04
    needs: [shared_values]
    steps:
      - id: step1
        run: |
          echo CHECKOUT=9bb56186c3b09b4f86b1c65136769dd318469633 >> $GITHUB_OUTPUT
          echo SETUP=943103cae7d3f1bb1e4951d5fcc7928b40e4b742 >> $GITHUB_OUTPUT
      - uses: actions/checkout@${{ steps.step1.outputs.CHECKOUT }}
      - uses: ruby/setup-ruby@${{ steps.step1.outputs.SETUP }}
      - run: ruby -v


      # - uses: actions/checkout@${{ needs.shared_values.outputs.checkout_sha }}
      # - uses: ruby/setup-ruby@${{ needs.shared_values.outputs.setup_ruby_sha }}
